name: CI
on: [workflow_dispatch]

env:
  BUILD_PROFILE: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild /p:Configuration=${{ env.BUILD_PROFILE }}
      - name: Extract Short Commit Hash
        id: extract
        shell: bash
        run: echo ::set-output name=commit::`git rev-parse --short HEAD`
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: NorthstarLauncher-${{ steps.extract.outputs.commit }}
          path: |
            x64/${{ env.BUILD_PROFILE }}/*.dll
            x64/${{ env.BUILD_PROFILE }}/*.exe
            x64/${{ env.BUILD_PROFILE }}/*.pdb
            x64/${{ env.BUILD_PROFILE }}/*.txt
      - name: CreateRelease
        uses: actions/create-release@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Automatically generated release by GitHubActions.
          draft: false
          prerelease: false
    
